version: '3.8'
services:
  db:
    image: postgres:15.5-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=123
    volumes:
      - data:/var/lib/postgresql/data
  main-service:
    build:
      context: ../MyJAAS
      dockerfile: src/Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=Admin
      - SPRING_DATASOURCE_PASSWORD=123
volumes:
  data: