create table if not exists users
(
    user_id  bigint generated by default as identity primary key,
    username varchar(100) not null,
    email    varchar(50)  not null unique,
    age      int          not null
);

create table if not exists account
(
    user_id bigint not null
        constraint user_id_fk
            references users (user_id) on delete cascade,
    login             varchar(30) primary key,
    password          varchar(70) not null,
    subscription      varchar(20) not null,
    is_locked_account boolean default (false),
    is_logged_out     boolean default (false)
);

create table if not exists user_role
(
    user_id bigint not null
        constraint user_id_fk
            references users (user_id) on delete cascade,
    role    varchar(20) not null,
    primary key (user_id, role)
);

create table if not exists initial_urls
(
    user_ip    varchar(15) primary key,
    url        varchar(200) not null unique,
    user_login varchar(30),
    appeal_method varchar(6)
);
